### ISSUE TITLE
# English rules need to be updated

### ISSUE THREAD

**Issue by HilbertXu** [RoboCupAtHomeJP/Rule2019#1]
Hello, I am a member of Team Kamerider, China
Because i know very a few about Japanese so it is pretty difficult for me to read Japanese rules.

And i notice that English rules have not been updated since 26 days ago, So could you please update the English rules timely

Thanks you a lot!

**Comment by HilbertXu** [comment]
And is the command generator of Go Get it Task available for us?
Or can we get some documents about the grammar or principle of the generator?

**Comment by yhagiwara** [comment]
Thanks for your questions on Go Get it Task.
I am TC of Go Get it Task.
The command generator of Go Get it task is not available for teams, but examples of commands are provided in the rules.
"Bring me a juice near the standing person."
"Bring me a red object in front of the TV."
The commands begin with "Bring me", followed by words that identify the object, such as object category, appearance, and position.
This task requires the ability to generalize the knowledge of objects and furniture in the environment and adapt to various linguistic expressions.

**Comment by HoriThe3rd** [comment]
@HilbertXu 
>And i notice that English rules have not been updated since 26 days ago, So could you please update the English rules timely

Thank you for your comment.
I'm sorry for the inconvenience but we are preparing the English version rules.
We will be able to release the rules in a few days.

**Comment by HilbertXu** [comment]
@HoriThe3rd 
Thank you very much for your reply.
I will wait for the newest English rules

**Comment by HilbertXu** [comment]
@yhagiwara 
Thank you for your clear explanation.
I will keep working for it.

**Comment by yuma116** [comment]
All OPL/DSPL english version rules were updated.
We apologized for the inconvenience.
