### ISSUE TITLE
Alternative Human-Robot interfaces

### ISSUE THREAD

**Issue by KMiyawaki** [RoboCupAtHomeJP/Rule2019#3]
大工大の宮脇です。お世話になっております。
（日本語で質問してもよいのでしょうか）
タッチパネルなどのAlternative Human-Robot interfacesは本家ルールブックだとRIPSでチェックを受けるように書かれていると思いますが（2018ルールならP49）、今回のジャパンオープンでも同じでしょうか。
それとも、RIPS外でチェックを受けてそのまま使えますでしょうか。

**Comment by Tamukoh** [comment]
2018ルールを適用しますので，チェックが必要と思われるものはRIPSでロボットに搭載しておいていただければと思います．

**Comment by KMiyawaki** [comment]
ありがとうございます。RIPS時にチェックを受けるようにします。
