### ISSUE TITLE
Basic Functionalities. Waiting start command

### ISSUE THREAD

**Issue by KMiyawaki** [RoboCupAtHomeJP/Rule2019#4]
大工大 OIT-Trialです。お世話になっております。

今回のBasic Functionは世界大会2014ルール
https://docs.google.com/viewer?a=v&pid=sites&srcid=cm9ib2N1cGF0aG9tZS5vcmd8cm9ib2N1cC1ob21lfGd4OjEzYWQ0MzQwYjdhYmQyODM
がもとになっていると思います。

その場合、P40に
To avoid logistic issues, whenever a robot has finished one atomic test, it should wait inside its current area for a command from one team member (i.e. a move/stop gesture or spoken move/stop commands) to start the next atomic test.

とあり、一つのテストが終了するごとにロボットは開始の合図を待つ必要があると思いますが、紹介動画では特にそのような様子は無かったと思います。
https://youtu.be/8OoxJS_4YFs

今回は省略可能（コマンド待ち受けがあっても良い）という考えでよろしいでしょうか。

**Comment by yuma116** [comment]
紹介動画のようにロボットは開始の合図を待つ必要はありません（1台ずつ実施されるため）．ただし，音声等で明確に開始することを示してください．
なお，開始の合図を待つ仕様にしていただいても構いません（柔軟に対応したいと思います）．

**Comment by KMiyawaki** [comment]
ありがとうございます。よく分かりました。
